# fly.toml app configuration file generated for eazy-italian on 2025-08-22T19:45:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "eazy-italian"
primary_region = "iad"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "eazy_italian_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 5432
  processes = ["app"]

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]
    force_https = false

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  protocol = "tcp"
  internal_port = 6379
  processes = ["app"]

  [[services.ports]]
    port = 6379
    handlers = ["redis"]
    force_https = false

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
