"""
app/services/slide_image_service.py
====================================
SlideImageService — enriches a SlideDeck with AI-generated images.

Flow
----
1. Caller passes a SlideDeck (already generated by SlideGeneratorService).
2. For each slide, SlideImageService builds a targeted image prompt via
   ImagePromptBuilder, using the slide's title and bullet points.
3. The prompt is sent to the injected ImageProvider.
4. The data URI returned by ImageResult.as_data_uri() is written directly
   to Slide.image (Optional[str]) — no intermediate SlideImage wrapper.
5. The enriched SlideDeck is returned.

Design principles
-----------------
* ImageProvider is injected — swap SVG, HuggingFace, or Null freely.
* Image generation is concurrent: all slides are generated in parallel
  via asyncio.gather() to minimise total latency.
* Failures on individual slides are caught and replaced with a
  NullImageProvider placeholder — one bad image never kills the deck.
* Slide.image is now Optional[str] (a data URI) rather than a nested
  SlideImage object, simplifying serialisation and frontend consumption.
* Prompt construction is delegated to ImagePromptBuilder.

Usage
-----
    from app.services.ai.image_providers.svg_provider import SVGImageProvider
    from app.services.ai.providers.ollama import LocalLlamaProvider
    from app.services.slide_image_service import SlideImageService

    text_provider = LocalLlamaProvider()
    img_provider  = SVGImageProvider(ai_provider=text_provider)
    img_service   = SlideImageService(image_provider=img_provider)

    # deck is a SlideDeck returned by SlideGeneratorService
    enriched_deck = await img_service.enrich_deck(deck)
    # enriched_deck.slides[i].image is now a data URI string
"""

from __future__ import annotations

import asyncio
import logging
from typing import Optional

from app.schemas.slides import Slide, SlideDeck
from app.services.ai.image_providers.image_base import (
    ImageProvider,
    ImageProviderError,
    NullImageProvider,
)
from app.services.image_prompt_builder import ImagePromptBuilder

logger = logging.getLogger(__name__)


class SlideImageService:
    """
    Attaches AI-generated images to every slide in a SlideDeck.

    Parameters
    ----------
    image_provider : ImageProvider
        Any concrete ImageProvider (SVG, HuggingFace, Null…).
    concurrency : int
        Max simultaneous image generation calls.
        Default 3 — safe for free-tier APIs.
    skip_intro_slide : bool
        Don't generate an image for slide 0 (usually a title slide).
    skip_summary_slide : bool
        Don't generate an image for the last slide (usually a recap).
    style : str
        Style keywords passed to every image prompt.
        E.g. "flat illustration, blue and white, educational".
    topic : str
        Deck topic forwarded to ImagePromptBuilder for richer prompts.
    target_audience : str
        Audience description forwarded to ImagePromptBuilder.
    """

    def __init__(
        self,
        image_provider:     ImageProvider,
        concurrency:        int  = 3,
        skip_intro_slide:   bool = False,
        skip_summary_slide: bool = False,
        style:              str  = "educational, flat illustration, clean background",
        topic:              str  = "",
        target_audience:    str  = "",
    ) -> None:
        if not isinstance(image_provider, ImageProvider):
            raise TypeError(
                f"image_provider must be an ImageProvider instance, "
                f"got {type(image_provider)}"
            )
        self._provider          = image_provider
        self._concurrency       = max(1, concurrency)
        self._skip_intro        = skip_intro_slide
        self._skip_summary      = skip_summary_slide
        self._style             = style
        self._topic             = topic
        self._audience          = target_audience
        self._null              = NullImageProvider()

    # ── Public API ─────────────────────────────────────────────────────────────

    async def enrich_deck(self, deck: SlideDeck) -> SlideDeck:
        """
        Concurrently generate images for all slides and return the
        enriched deck.  Individual slide failures are caught and replaced
        with a placeholder — the deck is always returned intact.

        Parameters
        ----------
        deck : SlideDeck
            Output from SlideGeneratorService.

        Returns
        -------
        SlideDeck
            Same deck with each Slide.image field populated as a data URI string.
        """
        n = len(deck.slides)
        logger.info(
            "Enriching deck with images — slides=%d provider=%r concurrency=%d",
            n, self._provider, self._concurrency,
        )

        # Build (index, slide) pairs that actually need images
        tasks = []
        for i, slide in enumerate(deck.slides):
            if self._skip_intro and i == 0:
                tasks.append(None)
                continue
            if self._skip_summary and i == n - 1:
                tasks.append(None)
                continue
            tasks.append((i, slide))

        # Run with bounded concurrency using a semaphore
        sem      = asyncio.Semaphore(self._concurrency)
        results  = await asyncio.gather(
            *[self._safe_generate(task, sem) for task in tasks],
            return_exceptions=False,
        )

        # Stitch images back onto slide copies.
        # Slide.image is Optional[str] — a plain data URI — so we call
        # result.as_data_uri() directly instead of wrapping in a SlideImage object.
        enriched_slides = []
        for slide, image_result in zip(deck.slides, results):
            enriched_slides.append(
                slide.model_copy(
                    update={"image": image_result.as_data_uri() if image_result else None}
                )
            )

        return deck.model_copy(update={"slides": enriched_slides})

    # ── Private helpers ────────────────────────────────────────────────────────

    async def _safe_generate(self, task, sem: asyncio.Semaphore):
        """
        Generate one image with semaphore throttling.
        Returns None for skipped slides.
        Catches all errors and returns a placeholder ImageResult.
        """
        if task is None:
            return None

        index, slide = task
        prompt   = self._build_image_prompt(slide, self._topic, self._audience, self._style)
        alt_text = f"Diagram illustrating: {slide.title}"

        async with sem:
            try:
                result = await self._provider.agenerate_image(
                    prompt   = prompt,
                    alt_text = alt_text,
                    style    = self._style,
                )
                logger.debug(
                    "Slide %d image OK — source=%s chars/bytes=%d",
                    index, result.source, len(result.data),
                )
                return result

            except (ImageProviderError, Exception) as exc:
                logger.error(
                    "Slide %d image generation failed: %s",
                    index, exc, exc_info=True,
                )
                return self._null.generate_image(
                    prompt   = prompt,
                    alt_text = alt_text,
                )

    @staticmethod
    def _build_image_prompt(
        slide:    Slide,
        topic:    str = "",
        audience: str = "",
        style:    str = "",
    ) -> str:
        """
        Delegate to ImagePromptBuilder for a structured, rich prompt.

        Kept as a static method so existing tests that call it directly
        continue to work without modification.
        """
        return ImagePromptBuilder.build(
            slide_title   = slide.title,
            bullet_points = slide.bullet_points,
            topic         = topic,
            audience      = audience,
            style         = style,
        )

    def __repr__(self) -> str:
        return (
            f"<SlideImageService provider={self._provider!r} "
            f"concurrency={self._concurrency}>"
        )