import { useCallback, useMemo, useRef, useState } from 'react';
import { Check, Plus, Sparkles, Upload, X } from 'lucide-react';
import ExerciseHeader, {
  EXERCISE_HEADER_HEIGHT_PX,
} from '../exercise/ExerciseHeader';
import api from '../../../../services/api';
import './DragToGap.css';
import AIExerciseGeneratorModal, { GeneratedBlock } from './AI_generation/AIExerciseGeneratorModal';

export interface DragToImageCard {
  id: string;
  imageUrl: string;
  answer: string;
  /** Optional scene description generated by AI — shown as a hint below the image slot */
  description?: string;
}

export interface DragToImageData {
  title: string;
  cards: DragToImageCard[];
}

interface Props {
  initialTitle?: string;
  initialData?: DragToImageData;
  label?: string;
  showWordsBar?: boolean;
  onSave: (data: DragToImageData, blockId?: string) => void;
  onCancel: () => void;
  segmentId?: string | number | null;
  exerciseType?: 'drag_to_image' | 'type_word_to_image';
}

let cardCounter = 0;
const newCardId = () => `dti_${++cardCounter}_${Date.now()}`;

function createEmptyCard(): DragToImageCard {
  return {
    id: newCardId(),
    imageUrl: '',
    answer: '',
  };
}

export type { Props as DragWordToImageEditorProps };

export default function DragWordToImageEditorPage({
  initialTitle = '',
  initialData,
  label = 'Перенести слово к изображению',
  showWordsBar = true,
  exerciseType = 'drag_to_image',
  onSave,
  onCancel,
  segmentId,
}: Props) {
  const [title, setTitle] = useState(initialData?.title ?? initialTitle);
  const [cards, setCards] = useState<DragToImageCard[]>(
    initialData?.cards?.length ? initialData.cards : [createEmptyCard()],
  );
  const [showAIModal, setShowAIModal] = useState(false);
  const [uploadingCardId, setUploadingCardId] = useState<string | null>(null);
  const [uploadErrors, setUploadErrors] = useState<Record<string, string>>({});
  const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({});
  // Holds the server-assigned block id when AI generation persisted the block.
  // Passed to onSave so handleExerciseSave reuses it instead of generating a
  // new random id that would create a duplicate block on the segment.
  const generatedBlockIdRef = useRef<string | null>(null);

  const filledChips = useMemo(
    () =>
      cards
        .map((card) => ({ id: card.id, word: card.answer.trim() }))
        .filter(({ word }) => word !== ''),
    [cards],
  );

  // Require a complete card before saving: each card needs an uploaded image
  // and a non-empty answer; also block save while an upload is in progress.
  const canSave =
    cards.length > 0 &&
    uploadingCardId === null &&
    cards.every(
      (card) => card.imageUrl.trim() !== '' && card.answer.trim() !== '',
    );

  const updateCard = (cardId: string, patch: Partial<DragToImageCard>) => {
    setCards((prev) =>
      prev.map((card) => (card.id === cardId ? { ...card, ...patch } : card)),
    );
  };

  const addCard = () => {
    setCards((prev) => [...prev, createEmptyCard()]);
  };

  const removeCard = (cardId: string) => {
    setCards((prev) => {
      if (prev.length === 1) return prev;
      return prev.filter((card) => card.id !== cardId);
    });
  };

  const handleSave = () => {
    if (!canSave) return;
    // Pass the AI-assigned block id so handleExerciseSave reuses it instead
    // of generating a fresh random id that would create a duplicate block.
    onSave({
      title: title.trim(),
      cards: cards.map((card) => ({
        ...card,
        answer: card.answer.trim(),
      })),
    }, generatedBlockIdRef.current ?? undefined);
  };

  // The backend emits kind="drag_word_to_image" while the editor can be opened
  // with exerciseType="drag_to_image" (the registered block kind).
  // Accept both aliases so AI-generated cards are never silently discarded.
  const applyGeneratedBlock = useCallback((block: GeneratedBlock) => {
    const ACCEPTED_KINDS = new Set(["drag_word_to_image", "drag_to_image", exerciseType]);
    if (!ACCEPTED_KINDS.has(block.kind) || !block.data || typeof block.data !== 'object') return;
    // Capture the server-assigned id for use when the user saves the editor.
    generatedBlockIdRef.current = block.id;
    const d = block.data as DragToImageData;
    setTitle(typeof d.title === 'string' ? d.title : block.title ?? '');
    setCards(
      Array.isArray(d.cards) && d.cards.length > 0
        ? [...d.cards]
        : [createEmptyCard()],
    );
  }, [exerciseType]);

  const handleImageUpload = async (cardId: string, file?: File) => {
    if (!file) return;

    setUploadingCardId(cardId);
    setUploadErrors((prev) => {
      const next = { ...prev };
      delete next[cardId];
      return next;
    });

    try {
      const formData = new FormData();
      formData.append('file', file);
      const response = await api.post<Record<string, string | undefined>>(
        '/tests/questions/upload-image',
        formData,
        {
          headers: {
            'Content-Type': 'multipart/form-data',
          },
        },
      );
      const result = response.data ?? {};
      const imageUrl =
        result.url ?? result.image_url ?? result.file_url ?? result.path ?? '';

      if (!imageUrl) {
        throw new Error('Image upload did not return a usable URL.');
      }

      updateCard(cardId, { imageUrl });
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Failed to upload image.';
      setUploadErrors((prev) => ({ ...prev, [cardId]: message }));
    } finally {
      setUploadingCardId((prev) => (prev === cardId ? null : prev));
      if (fileInputRefs.current[cardId]) {
        fileInputRefs.current[cardId]!.value = '';
      }
    }
  };

  return (
    <div className="dtg-editor-root">
      <ExerciseHeader
        title={title}
        headerLabel={label}
        editableTitleInHeader={false}
        onClose={onCancel}
      />

      <div
        className="dtg-editor-content"
        style={{ paddingTop: EXERCISE_HEADER_HEIGHT_PX + 14 }}
        aria-label={label}
      >
        <div className="dtg-title-row">
          <input
            className="dtg-title-input"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Exercise title (shown to students)"
            aria-label="Exercise title"
          />
        </div>

        {/* ── Student-facing preview: instruction shown in the block */}
        <div className="dtg-editor-title-preview">
          <div className="dtg-exercise-instruction">
            Drag words onto the correct images
          </div>
        </div>

        {showWordsBar && (
          <div className="dtg-words-bar">
            {filledChips.length === 0 ? (
              <span className="dtg-words-bar-hint">
                Слова появятся здесь после заполнения карточек
              </span>
            ) : (
              filledChips.map(({ id, word }) => (
                <span key={id} className="dtg-chip dtg-chip--bar">
                  {word}
                </span>
              ))
            )}
          </div>
        )}

        <div className="dti-editor-board" aria-label="Image answer cards">
          {cards.map((card, index) => {
            const isFilled = card.answer.trim() !== '';
            const hasImage = card.imageUrl.trim() !== '';
            const isUploading = uploadingCardId === card.id;
            const uploadError = uploadErrors[card.id];

            return (
              <div key={card.id} className="dti-editor-card">
                {index > 0 && (
                  <button
                    type="button"
                    className="dti-editor-card-remove"
                    onClick={() => removeCard(card.id)}
                    aria-label="Remove image card"
                    title="Удалить карточку"
                  >
                    <X size={14} />
                  </button>
                )}

                <input
                  ref={(el) => {
                    fileInputRefs.current[card.id] = el;
                  }}
                  type="file"
                  accept="image/*"
                  style={{ display: 'none' }}
                  onChange={(e) => {
                    void handleImageUpload(card.id, e.target.files?.[0]);
                  }}
                />

                <button
                  type="button"
                  className={[
                    'dti-image-slot',
                    hasImage ? 'dti-image-slot--filled' : '',
                  ]
                    .filter(Boolean)
                    .join(' ')}
                  disabled={isUploading}
                  onClick={() => fileInputRefs.current[card.id]?.click()}
                  aria-label={hasImage ? 'Replace image' : 'Upload image'}
                  title={hasImage ? 'Заменить изображение' : 'Загрузить изображение'}
                >
                  {hasImage ? (
                    <img
                      src={card.imageUrl}
                      alt=""
                      className="dti-image-slot-preview"
                    />
                  ) : (
                    <span className="dti-image-slot-upload">
                      <Upload size={18} />
                      <span>{isUploading ? 'Uploading...' : 'Upload'}</span>
                    </span>
                  )}
                </button>

                <div className="dti-answer-row">
                  <input
                    type="text"
                    value={card.answer}
                    onChange={(e) => updateCard(card.id, { answer: e.target.value })}
                    className="dti-answer-input"
                    placeholder="Correct word"
                    aria-label="Correct word"
                  />
                  <span
                    className={[
                      'dtg-dot',
                      isFilled ? 'dtg-dot--green' : 'dtg-dot--empty',
                    ].join(' ')}
                    aria-hidden="true"
                  />
                </div>

                {/* AI-generated scene description — used as image hint */}
                {card.description && (
                  <p className="dti-card-description" title="AI image hint">
                    {card.description}
                  </p>
                )}

                {uploadError && (
                  <div className="dti-upload-error" role="alert">
                    {uploadError}
                  </div>
                )}
              </div>
            );
          })}

          <button
            type="button"
            className="dti-add-card"
            onClick={addCard}
            aria-label="Add image card"
            title="Добавить карточку"
          >
            <Plus size={18} />
          </button>
        </div>

        {/* FIX 2: onClick was missing — button rendered but never set showAIModal to true */}
        <button
          type="button"
          className="dtg-generate-btn"
          onClick={() => setShowAIModal(true)}
        >
          <Sparkles size={13} />
          Сгенерировать
        </button>

        <AIExerciseGeneratorModal
          exerciseType={exerciseType}
          open={showAIModal}
          onClose={() => setShowAIModal(false)}
          segmentId={segmentId}
          onGenerated={(block) => {
            applyGeneratedBlock(block);
          }}
        />

        <div className="dtg-footer">
          <div className="dtg-footer-btns">
            <button type="button" className="dtg-btn-cancel" onClick={onCancel}>
              Отмена
            </button>
            <button
              type="button"
              className={[
                'dtg-btn-save',
                !canSave ? 'dtg-btn-save--disabled' : '',
              ]
                .filter(Boolean)
                .join(' ')}
              onClick={handleSave}
              disabled={!canSave}
              title={
                !canSave
                  ? 'Добавьте изображение и слово в каждую карточку'
                  : 'Сохранить упражнение'
              }
            >
              <Check size={14} />
              Сохранить
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}